//go:build amd64 && amd64.v2

// Code generated by wasm2go (gcasm backend). DO NOT EDIT.
//
// Import calls live in assembly, invisible to the linker's
// method pruning, which would fill every itab slot with
// runtime.unreachableMethod. init() is always reachable, so
// the never-taken calls below emit genuine interface call
// sites that pin each method. gcasmKeepAlive is never set.

package base

var gcasmKeepAlive bool

func init() {
	if !gcasmKeepAlive {
		return
	}
	(EnvImports)(nil).Emscripten_pc_get_function(nil, 0)
	(EnvImports)(nil).Emscripten_stack_snapshot(nil)
	(EnvImports)(nil).Emscripten_stack_unwind_buffer(nil, 0, 0, 0)
	(EnvImports)(nil).X_ZN4absl12lts_2026010712log_internal12ExitOnDFatalEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2026010712log_internal13IsInitializedEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2026010712log_internal13WriteToStderrENSt3__217basic_string_viewIcNS2_11char_traitsIcEEEENS0_11LogSeverityE(nil, 0, 0)
	(EnvImports)(nil).X_ZN4absl12lts_2026010712log_internal24MaxFramesInLogStackTraceEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2026010712log_internal24SetSuppressSigabortTraceEb(nil, 0)
	(EnvImports)(nil).X_ZN4absl12lts_2026010712log_internal28ShouldSymbolizeLogStackTraceEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2026010712log_internal8TimeZoneEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2026010713time_internal4cctz12TimeZoneLibC4MakeERKNSt3__212basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE(nil, 0)
	(EnvImports)(nil).X_ZN4absl12lts_2026010716raw_log_internal6RawLogENS0_11LogSeverityEPKciS4_z(nil, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN6google7spanner8emulator7backend17RemoteUdfProtocol11FingerprintEN4absl12lts_202601074SpanIKN9googlesql5ValueEEE(nil, 0, 0)
	(EnvImports)(nil).X_ZN6google7spanner8emulator7backend17RemoteUdfProtocol6ToJsonERKN9googlesql5ValueE(nil, 0, 0)
	(EnvImports)(nil).X_ZN6google7spanner8emulator7backend17RemoteUdfProtocol7ToValueEN9googlesql17JSONValueConstRefEPKNS4_4TypeE(nil, 0, 0, 0)
	(EnvImports)(nil).X_ZN6google7spanner8emulator7backend17RemoteUdfProtocol7ToValueEyPKN9googlesql4TypeE(nil, 0, 0, 0)
	(EnvImports)(nil).X_ZN6google7spanner8emulator7backend18RemoteUdfEvaluator14BuildEvaluatorENSt3__212basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEESA_PKN9googlesql4TypeE(nil, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN6google7spanner8emulator7backend18RemoteUdfEvaluator22EvaluateRemoteFunctionENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_N4absl12lts_202601074SpanIKN9googlesql5ValueEEE(nil, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql14FirstCharLowerENSt3__217basic_string_viewIcNS0_11char_traitsIcEEEE(nil, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql15GetErrorSourcesERKN4absl12lts_202601076StatusE(nil, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql15MakeErrorSourceERKN4absl12lts_202601076StatusENSt3__217basic_string_viewIcNS5_11char_traitsIcEEEENS_16ErrorMessageModeE(nil, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql20ShouldPropagateErrorERKN4absl12lts_202601076StatusE(nil, 0)
	(EnvImports)(nil).X_ZN9googlesql22EvaluateQuantifiedLikeERKNS_30QuantifiedLikeEvaluationParamsE(nil, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql24TokenListFromStringArrayENSt3__26vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS5_IS7_EEEEb(nil, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql28RegisterBuiltinJsonFunctionsEv(nil)
	(EnvImports)(nil).X_ZN9googlesql28RegisterBuiltinUuidFunctionsEv(nil)
	(EnvImports)(nil).X_ZN9googlesql29RegisterBuiltinRangeFunctionsEv(nil)
	(EnvImports)(nil).X_ZN9googlesql29StatusesToDeprecationWarningsEN4absl12lts_202601074SpanIKNS1_6StatusEEENSt3__217basic_string_viewIcNS6_11char_traitsIcEEEE(nil, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql31GetDefaultErrorMessageStabilityEv(nil)
	(EnvImports)(nil).X_ZN9googlesql31StatusWithInternalErrorLocationERKN4absl12lts_202601076StatusERKNS_18ParseLocationPointE(nil, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql32DeprecationWarningsToDebugStringEN4absl12lts_202601074SpanIKNS_30FreestandingDeprecationWarningEEE(nil, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql8internal15GetPublicSuffixENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(nil, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql8internal19GetTopPrivateDomainENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(nil, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions12ZstdCompressENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEx(nil, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions14ZstdDecompressENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEbx(nil, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions15FarmFingerprintENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(nil, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions22SplitUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_PNS4_6vectorIS8_NS4_9allocatorIS8_EEEEPN4absl12lts_202601076StatusE(nil, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions24ReplaceUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_S8_PNS4_12basic_stringIcS7_NS4_9allocatorIcEEEEPN4absl12lts_202601076StatusE(nil, 0, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions24SplitSubstrWithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_xxPNS4_12basic_stringIcS7_NS4_9allocatorIcEEEE(nil, 0, 0, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions25EndsWithUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_PbPN4absl12lts_202601076StatusE(nil, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions27StartsWithUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_PbPN4absl12lts_202601076StatusE(nil, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions33StrPosOccurrenceUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_xxPxPN4absl12lts_202601076StatusE(nil, 0, 0, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN9googlesql9functions6Hasher6CreateENS1_9AlgorithmE(nil, 0)
	(EnvImports)(nil).X__cxa_allocate_exception(nil, 0)
	(EnvImports)(nil).X__cxa_throw(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Clock_time_get(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_sizes_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_close(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_fdstat_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_fdstat_set_flags(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_dir_name(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_read(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_seek(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_write(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_open(nil, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Poll_oneoff(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Proc_exit(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Random_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sched_yield(nil)
}
